
jwt:
  secret: "753778214125442A472D4B6150645367566B59703373367639792F423F452848"
  expiration: 36000000 # 10 soat millisekundlarda

spring:
  application:
    name: USM

  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: 1483
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
